UBUNTU: Drop definition of DMI_EXACT_MATCH
BugLink: http://bugs.launchpad.net/bugs/1319885

The definition of DMI_EXACT_MATCH is now defined with the backport of upstream
commit 5017b2851373ee15c7035151853bb1448800cae2 ("dmi: add support for exact DMI
matches in addition to substring matching") in the kernel.

This causes a build failure with:

... cw-3.11/backport-include/linux/mod_devicetable.h:6:0: error: "DMI_EXACT_MATCH" redefined [-Werror]

This patch simply drops the definition of this macro from -lbm.

Signed-off-by: Luis Henriques <luis.henriques@canonical.com>